apiVersion: v1
kind: Secret
metadata:
  name: secureflow-secrets
  namespace: default
type: Opaque
stringData:
  database-url: postgresql://postgres:postgres@secureflow-postgres-svc:5432/secureflow
  jwt-secret-key: your-super-secure-production-jwt-signing-secret-key-phrase
  aws-access-key-id: AKIAIOSFODNN7EXAMPLE
  aws-secret-access-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
